#!/bin/bash
export JOBNAME="rose_fromBT2"
#PBS -N ${JOBNAME}
#PBS -l walltime=100:00:00
#PBS -l nodes=1:ppn=40
#PBS -q q40

# Comments:
# Created on 04/03/18 by Foon Wong for math and biology collaboration effort headed by Dr. Sam Behseta and Dr. Parvin Shahrestani.

# Setup environment variables source 
source $HOME/jobscripts/metaphlan2/metaphlan2.env

# Define input data source 
export IN_DIR=$PBS_O_WORKDIR

# Define output directory
export OUT_DIR=$PBS_O_WORKDIR

# Change to biomath group which has access to input data
newgrp biomath

conda activate py27

# Run the MetaPhlAn command with all of the parameters.
export M2PS="--nproc 20 --input_type bowtie2out --ignore_markers $HOME/jobscripts/*filter.txt"
metaphlan2.py ${M2PS} -o ${OUT_DIR}/${NM}.profile ${IN_DIR}/${NM}*.bz2 

conda deactivate
